### ISSUE TITLE
Item macro raises a undefined 'config' exception

### ISSUE THREAD

**Issue by patrickporto** [md5crypt/item-macro-chat-buttons#1]
Hello

I have been using simple world building, and I have tried to create a item macro like the following:
```js
item.useWithButtons(args, [
	{
		label: "Draw From Roll Table",
		icon: "fa-dice",
		callback: async () => {
			let table = await game.packs.get("world.roll-tables").getDocument("TgjUynKRArpImDkn");
			let roll = await new Roll(table.formula, actor.getRollData()).roll()
			await game.dice3d?.showForRoll(roll, game.user, true)
			table.toMessage(
				table.getResultsForRoll(roll.total),
				{roll, messageData:{speaker}}
			)
		}
	}
])
```

I have received the following exception:
```
index.js:39 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'config')
    at SimpleItem.useWithButtons (index.js:39:43)
    at Macro.eval (eval at Item._executeScript (helper.js:85:18), <anonymous>:3:6)
    at Item._executeScript (helper.js:91:36)
    at Item.executeMacro (helper.js:62:29)
    at HTMLHeadingElement.<anonymous> (helper.js:190:18)
    at HTMLHeadingElement.dispatch (jquery.min.js:2:40035)
    at v.handle (jquery.min.js:2:38006)
```

I believe that the issue is happened because args is empty, but I don't know what I could do differently.

**Comment by md5crypt** [comment]
huh, weird, try to provide a bit more info

1. when exactly do you get that error (on item roll? how is the item roll initiated? from character sheet?)
2. what system are you using and versions of core system and item macro plugin
3. add `console.log(args)` before `item.useWithButtons(args, [` and check what is in args

note that I tested this plugin only on dnd5e as that's what I'm using for my sessions. 🤷It might need a few tweaks to support other systems.

**Comment by md5crypt** [comment]
OK, "simple world building" is a system, did not know that.

I'm sorry but I don't see it working with that because from what I see that system does not support rolling items at all (unless I did not find rolling items in the 5min I played with it).

This plugin does not create chat messages from scratch, it just amends roll item messages created by the system.
